# Example secrets.toml file for Streamlit Cloud
# Copy this to the Streamlit Cloud secrets management console
# Do NOT commit the actual secrets.toml file to GitHub

# Each project should be under the [projects] section
[projects]

# Default project that will be used if no specific project is selected
[projects.default]
ACCESS_KEY = "dfe0-cec0-6eed-41ab-af2f-90c9-7bf0e698"
SECRET_KEY = "949a-eb70-5383-4506-84f7-efc7-a538d390"
API_GATEWAY = "https://ag-eu2.envisioniot.com"
ORG_ID = "o16779139592841674"
PROJECT_NAME = "Default Project"

# Additional projects can be defined here
[projects.Concorde]
ACCESS_KEY = "dfe0-cec0-6eed-41ab-af2f-90c9-7bf0e698"
SECRET_KEY = "949a-eb70-5383-4506-84f7-efc7-a538d390"
API_GATEWAY = "https://ag-eu2.envisioniot.com"
ORG_ID = "o16779139592841674"
PROJECT_NAME = "Concorde"

[projects.CAG]
ACCESS_KEY = "a19a-81ad-3310-4f9b-a84d-2482-d6d9a947"
SECRET_KEY = "1294-a0ea-e074-44be-ae2c-4180-ffd68960"
API_GATEWAY = "https://apim-sg1.envisioniot.com"
ORG_ID = "o17134091232951160"
PROJECT_NAME = "CAG"

# Note: The above keys are examples only with hyphens added.
# Replace with your actual API keys when setting up in Streamlit Cloud
# Make sure your keys follow the required format with hyphens 